### ISSUE TITLE
Brackets doesn't seem to match the color scheme

### ISSUE THREAD

**Issue by Aricha9801** [ilof2/posterpole.nvim#8]
Using the style in VScode. It looks like () and [] have a bright color, not matching the overall color scheme.
<img width="464" alt="image" src="https://github.com/user-attachments/assets/eae47207-d7bf-4f7d-b485-a55710879219">

**Comment by ilof2** [comment]
Fixed, but please in the future make sure you are creating issues in the right repo
For vscode https://github.com/posterpole/vscode
